//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeAndForSale
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public string username { get; set; }
        public int productID { get; set; }
        public string productName { get; set; }
        public string category { get; set; }
        public Nullable<int> price { get; set; }
        public System.DateTime postedDate { get; set; }
        public string productInfo { get; set; }
        public string deliveryType { get; set; }
        public byte[] photo1 { get; set; }
        public byte[] photo2 { get; set; }
    }
}
